name: my_log
version: 1.0.2+8
description: A powerful Flutter logging package with colored logs, file logging, and real-time log display on screen.
repository: https://github.com/ngmduc2012/my_log.git
funding:
  - https://buymeacoffee.com/ducmng12g
  - https://ko-fi.com/I2I81AEJG8

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  logger: ^2.5.0
  flutter_staggered_animations: ^1.1.1
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

screenshots:
  - description: "dialog log"
    path: avatar.png

topics:
  - log
  - color
  - save-file
  - popup-realtime-log
